language: node_js
node_js:
  - "10"
before_install:
  - npm install -g firebase-tools
script:
  - npm i
  - npm test
  - cp -R node_modules functions/
  - cd functions
  - npm i
  - npm run lint
  - cd ..
  - sh firebaseDeploy.sh
cache:
  npm: true
  directories:
    - node_modules/
    - functions/node_modules/
