language: node_js
node_js:
- '10'
script:
- 
deploy:
  provider: firebase
  token:
    secure: ppeeOb5uc2vELS7/cV3i1dOseM+29cAJxeyZaxQzNy0bN5P/e8IAIEoqwGzwwIlcQ4lNRooiJOSDKH1L7k4pY9zh/eiFuqAsCYJcjICRAWUdzzatSuefRFDHzZCQ5YCBr9nwgrJTX4gswDkw/97pUY5h6+PjuxDlbsOe7WmAVfsdNRdBhv59A3Cq5LwAk/j9fUj66INab8YmmwLvzL7Fn4w2yRAlrzv1r0UutaZ92CYNw+gQZUdyexqAIBqhfkn3T01N+dIH8VOIaxuzHxDFmx//KljTfkorUwudzFniQEWAC32Luak1EyIZceBEYZ7fj948LbLENmnhBo2FUUWLD5caZm6vj4zg06Ee6EV23Zda37j66sKSlH0DbjRnzX9AOZZAh0G8SwdrgQogjoQNYef6V2xMbdpcf2fCoqKO0dgHPUXXpmACAlPnzKDFApOl1aR94HUjnJAobIxYjFM4AOYVCKKVnrg72waHLMc7GooIRO8UYay0MrKtvK9RFzudLvWhoL2s+L7ffKk/1oTUDU22K7yCW8tu2/jKEw8zEuMw043gZJqfSM3dE+J6IAruQv/Wcmpm6hAjcC9gfzR04bFxXmspAFXe5mlNWGEqWTl0R9bZLe8TLhdzkad2ny/hdxdtaiHER0uJ9irBv0L9cOpNEf67eNH+f0+N8sZ2TwY=